/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Oliver
 */
public class Bestilling extends javax.swing.JFrame {

    /**
     * Creates new form ordre
     */
    public Bestilling() {
        initComponents();
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Tlf_nr = new javax.swing.JLabel();
        jLabel_Fornavn = new javax.swing.JLabel();
        jLabel_Efternavn = new javax.swing.JLabel();
        jLabel_Adresse = new javax.swing.JLabel();
        jTextField_Tlf_Nr = new javax.swing.JTextField();
        jTextField_Fornavn = new javax.swing.JTextField();
        jTextField_Efternavn = new javax.swing.JTextField();
        jTextField_Adresse = new javax.swing.JTextField();
        jButton_Hent_Kunde = new javax.swing.JButton();
        jTextField_Post_Nr = new javax.swing.JTextField();
        jTextField_By = new javax.swing.JTextField();
        jLabel_By = new javax.swing.JLabel();
        jLabel_Post_Nr = new javax.swing.JLabel();
        jLabel_Hent_Kunde_Fejl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox_Ny_Sten = new javax.swing.JCheckBox();
        jCheckBox_Tilføjelse = new javax.swing.JCheckBox();
        jCheckBox_Gravsten = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Værkstedstimer = new javax.swing.JLabel();
        jLabel_Rensning = new javax.swing.JLabel();
        jLabel_Transport = new javax.swing.JLabel();
        jLabel_Afhentning = new javax.swing.JLabel();
        jLabel_Levering = new javax.swing.JLabel();
        jTextField_Værkstedstimer = new javax.swing.JTextField();
        jTextField_Rensning = new javax.swing.JTextField();
        jTextField_Afhentning = new javax.swing.JTextField();
        jTextField_Transport = new javax.swing.JTextField();
        jTextField_Levering = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel_Kirkegård = new javax.swing.JLabel();
        jLabel_Afdeling = new javax.swing.JLabel();
        jLabel_Gravtype = new javax.swing.JLabel();
        jTextField_Kirkegård = new javax.swing.JTextField();
        jTextField_Afdeling = new javax.swing.JTextField();
        jTextField_Gravtype = new javax.swing.JTextField();
        jButton_Videre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1024, 760));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Tlf_nr.setText("Tlf nr:");
        jPanel1.add(jLabel_Tlf_nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel_Fornavn.setText("Fornavn");
        jPanel1.add(jLabel_Fornavn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel_Efternavn.setText("Efternavn");
        jPanel1.add(jLabel_Efternavn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel_Adresse.setText("Adresse");
        jPanel1.add(jLabel_Adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));
        jPanel1.add(jTextField_Tlf_Nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 122, -1));
        jPanel1.add(jTextField_Fornavn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 122, -1));
        jPanel1.add(jTextField_Efternavn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 122, -1));
        jPanel1.add(jTextField_Adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 122, -1));

        jButton_Hent_Kunde.setText("Hent Kunde");
        jPanel1.add(jButton_Hent_Kunde, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 109, -1));
        jPanel1.add(jTextField_Post_Nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 122, -1));
        jPanel1.add(jTextField_By, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 122, -1));

        jLabel_By.setText("By");
        jPanel1.add(jLabel_By, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, 20));

        jLabel_Post_Nr.setText("Post nr");
        jPanel1.add(jLabel_Post_Nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, 20));

        jLabel_Hent_Kunde_Fejl.setText("Fejl Label");
        jPanel1.add(jLabel_Hent_Kunde_Fejl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 830, 190));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Kunde info");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        buttonGroup1.add(jCheckBox_Ny_Sten);
        jCheckBox_Ny_Sten.setText("Ny sten");
        jCheckBox_Ny_Sten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_Ny_StenActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_Ny_Sten, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        buttonGroup1.add(jCheckBox_Tilføjelse);
        jCheckBox_Tilføjelse.setText("Tilføjelse");
        jCheckBox_Tilføjelse.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox_TilføjelseStateChanged(evt);
            }
        });
        getContentPane().add(jCheckBox_Tilføjelse, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jCheckBox_Gravsten.setText("Gravsten");
        jCheckBox_Gravsten.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox_GravstenStateChanged(evt);
            }
        });
        getContentPane().add(jCheckBox_Gravsten, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Værkstedstimer.setText("Værkstedstimer");
        jPanel2.add(jLabel_Værkstedstimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 23, -1, -1));

        jLabel_Rensning.setText("Rensning");
        jPanel2.add(jLabel_Rensning, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 61, -1, -1));

        jLabel_Transport.setText("Transport");
        jPanel2.add(jLabel_Transport, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 99, -1, -1));

        jLabel_Afhentning.setText("Afhentning");
        jPanel2.add(jLabel_Afhentning, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 137, -1, -1));

        jLabel_Levering.setText("Levering");
        jPanel2.add(jLabel_Levering, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 175, -1, -1));
        jPanel2.add(jTextField_Værkstedstimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 20, 137, -1));
        jPanel2.add(jTextField_Rensning, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 58, 137, -1));
        jPanel2.add(jTextField_Afhentning, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 134, 137, -1));
        jPanel2.add(jTextField_Transport, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 96, 137, -1));
        jPanel2.add(jTextField_Levering, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 172, 137, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 380, 220));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Kirkegård.setText("Kirkegård");
        jPanel3.add(jLabel_Kirkegård, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel_Afdeling.setText("Afdeling");
        jPanel3.add(jLabel_Afdeling, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel_Gravtype.setText("Gravtype");
        jPanel3.add(jLabel_Gravtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel3.add(jTextField_Kirkegård, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 170, -1));
        jPanel3.add(jTextField_Afdeling, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 170, -1));
        jPanel3.add(jTextField_Gravtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 380, 220));

        jButton_Videre.setText("Videre");
        jButton_Videre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VidereActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Videre, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 180, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_Ny_StenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_Ny_StenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_Ny_StenActionPerformed

    private void jCheckBox_TilføjelseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox_TilføjelseStateChanged
        if (jCheckBox_Tilføjelse.isSelected()) {
            jPanel2.setVisible(true);

        } else {
            jPanel2.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_TilføjelseStateChanged

    private void jCheckBox_GravstenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox_GravstenStateChanged
        if (jCheckBox_Gravsten.isSelected()) {
            jPanel3.setVisible(true);
        }else{
            jPanel3.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_GravstenStateChanged

    private void jButton_VidereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VidereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_VidereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bestilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bestilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bestilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bestilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Bestilling().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Hent_Kunde;
    private javax.swing.JButton jButton_Videre;
    private javax.swing.JCheckBox jCheckBox_Gravsten;
    private javax.swing.JCheckBox jCheckBox_Ny_Sten;
    private javax.swing.JCheckBox jCheckBox_Tilføjelse;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Adresse;
    private javax.swing.JLabel jLabel_Afdeling;
    private javax.swing.JLabel jLabel_Afhentning;
    private javax.swing.JLabel jLabel_By;
    private javax.swing.JLabel jLabel_Efternavn;
    private javax.swing.JLabel jLabel_Fornavn;
    private javax.swing.JLabel jLabel_Gravtype;
    private javax.swing.JLabel jLabel_Hent_Kunde_Fejl;
    private javax.swing.JLabel jLabel_Kirkegård;
    private javax.swing.JLabel jLabel_Levering;
    private javax.swing.JLabel jLabel_Post_Nr;
    private javax.swing.JLabel jLabel_Rensning;
    private javax.swing.JLabel jLabel_Tlf_nr;
    private javax.swing.JLabel jLabel_Transport;
    private javax.swing.JLabel jLabel_Værkstedstimer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_Adresse;
    private javax.swing.JTextField jTextField_Afdeling;
    private javax.swing.JTextField jTextField_Afhentning;
    private javax.swing.JTextField jTextField_By;
    private javax.swing.JTextField jTextField_Efternavn;
    private javax.swing.JTextField jTextField_Fornavn;
    private javax.swing.JTextField jTextField_Gravtype;
    private javax.swing.JTextField jTextField_Kirkegård;
    private javax.swing.JTextField jTextField_Levering;
    private javax.swing.JTextField jTextField_Post_Nr;
    private javax.swing.JTextField jTextField_Rensning;
    private javax.swing.JTextField jTextField_Tlf_Nr;
    private javax.swing.JTextField jTextField_Transport;
    private javax.swing.JTextField jTextField_Værkstedstimer;
    // End of variables declaration//GEN-END:variables
}
