/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DatabaseObjectHandler;
import control.Utility;
import control.exceptions.ControlException;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Faktura;
import model.Faktureringsadresse;
import model.Kontoudtog;
import model.Kunde;
import model.Ordre;
import model.Postnummer;
import model.Provisionsseddel;
import model.Samarbejdspartner;

/**
 *
 * @author T
 */
public class JDialog_SøgOrdre extends javax.swing.JDialog {

    private Ordre ordre;
    private DatabaseObjectHandler dbhandler;
    private Panel_Søg panel;
    private Kunde kunde;

    /**
     * Creates new form JDialog_SøgFaktura
     */
    public JDialog_SøgOrdre(java.awt.Frame parent, boolean modal, DatabaseObjectHandler dbhandler, Ordre ordre) {
        super(parent, modal);
        this.dbhandler = dbhandler;
        this.ordre = ordre;
        kunde = ordre.getKunde();
        initComponents();
        jLabel_VisOprettet.setText(Utility.formatTimestampToString(ordre.getOrdredato()));
        jLabel_VisTlf.setText("" + kunde.getTlf());
        jLabel_VisAdresse.setText(kunde.getAdresse());
        jLabel_VisPostnrBy.setText(kunde.getPost_nr().getPost_nr() + " " + kunde.getPost_nr().getByNavn());
        jLabel_VisNavn.setText(kunde.getFornavn() + " " + kunde.getEfternavn());
        //jLabel_VisSendtDato.setText(Utility.formatTimestampToString();
        jLabel_VisPris.setText(NumberFormat.getCurrencyInstance().format(ordre.getTotal()));
        jLabel_VisAfhentDato.setText(Utility.formatTimestampToString(ordre.getAfhentningsdato()));
        jLabel_VisLevDato.setText(Utility.formatTimestampToString(ordre.getLeveringsdato()));
       
        if (ordre.getOrdretype()) {
            jLabel_VisAfDødNavn.setText(ordre.getAfdødnavn());
            jLabel_VisAfdeling.setText("" + ordre.getAfdeling());
            jLabel_VisNR.setText("" + ordre.getNummer());
            jLabel_VisRække.setText("" + ordre.getRække());
            jLabel_VisKirkegård.setText(ordre.getKirkegård().getNavn());
            jLabel_VisBemærkning.setText(ordre.getBemærkning());
            jLabel_VisBemærkning.setToolTipText(ordre.getBemærkning());
          
            if (!ordre.getBemærkning_ekstra().isEmpty()) {
                jLabel_VisEkstraBemærkning.setText(ordre.getBemærkning_ekstra());
                jLabel_VisEkstraBemærkning.setToolTipText(ordre.getBemærkning_ekstra());
            } else {
                jLabel_VisEkstraBemærkning.setText("Ingen ekstra bemærkning indtastet");
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_card = new javax.swing.JPanel();
        panel_visOrdre = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_VisNavn = new javax.swing.JLabel();
        jLabel_VisAdresse = new javax.swing.JLabel();
        jLabel_VisPostnrBy = new javax.swing.JLabel();
        jLabel_VisTlf = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_VisLevDato = new javax.swing.JLabel();
        jLabel_VisOprettet = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_VisProvision = new javax.swing.JLabel();
        jLabel_VisAfhentDato = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_VisPris = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton_OrdrePDF = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton_FakturaPdf = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton_Kontopdf = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel_Afdødnavn = new javax.swing.JLabel();
        jLabel_Kirkegård = new javax.swing.JLabel();
        jLabel_Række = new javax.swing.JLabel();
        jLabel_NR = new javax.swing.JLabel();
        jLabel_Afdeling = new javax.swing.JLabel();
        jLabel_Bemærkning = new javax.swing.JLabel();
        jLabel_VisAfDødNavn = new javax.swing.JLabel();
        jLabel_VisKirkegård = new javax.swing.JLabel();
        jLabel_VisRække = new javax.swing.JLabel();
        jLabel_VisNR = new javax.swing.JLabel();
        jLabel_VisAfdeling = new javax.swing.JLabel();
        jLabel_VisBemærkning = new javax.swing.JLabel();
        jLabel_VisEkstraBemærkning = new javax.swing.JLabel();
        jLabel_fejl = new javax.swing.JLabel();
        panel_Opgrader = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panel_faktura_info = new javax.swing.JPanel();
        button_accepter = new javax.swing.JButton();
        panel_fakturaInfo = new javax.swing.JPanel();
        radioButton_NormalOrdre = new javax.swing.JRadioButton();
        radioButton_Bedemand = new javax.swing.JRadioButton();
        textField_Faktura_nr = new javax.swing.JTextField();
        textField_ordreNr = new javax.swing.JTextField();
        label_ordre_nr = new javax.swing.JLabel();
        label_faktura_nr = new javax.swing.JLabel();
        textField_dato = new javax.swing.JTextField();
        label_dato = new javax.swing.JLabel();
        panel_faktureringsadresse = new javax.swing.JPanel();
        label_faktureringBy = new javax.swing.JLabel();
        label_faktureringPostNr = new javax.swing.JLabel();
        label_faktureringsadresse = new javax.swing.JLabel();
        textField_faktureringAdresse = new javax.swing.JTextField();
        checkBox_faktureringsAdresse = new javax.swing.JCheckBox();
        textField_faktureringPostNr = new javax.swing.JTextField();
        textField_faktureringBy = new javax.swing.JTextField();
        panel_bedemandInfo = new javax.swing.JPanel();
        label_bedemand_firma = new javax.swing.JLabel();
        label_bedemand_cvr = new javax.swing.JLabel();
        label_bedemand_adresse = new javax.swing.JLabel();
        label_bedemand_postnr = new javax.swing.JLabel();
        label_bedemand_by = new javax.swing.JLabel();
        label_bedemand_bank = new javax.swing.JLabel();
        label_bedemand_regnr = new javax.swing.JLabel();
        label_bedemand_kontonr = new javax.swing.JLabel();
        textField_bedemand_firma = new javax.swing.JTextField();
        textField_bedemand_adresse = new javax.swing.JTextField();
        textField_bedemand_post = new javax.swing.JTextField();
        textField_bedemand_by = new javax.swing.JTextField();
        textField_bedemand_kontonr = new javax.swing.JTextField();
        textField_bedemand_cvr = new javax.swing.JTextField();
        textField_bedemand_bank = new javax.swing.JTextField();
        textField_bedemand_regnr = new javax.swing.JTextField();
        textField_bedemand_tlf = new javax.swing.JTextField();
        label_bedemand_telefon = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        label_info_opgrader = new javax.swing.JLabel();
        button_annuller = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ordre");
        setMinimumSize(new java.awt.Dimension(470, 430));
        setPreferredSize(new java.awt.Dimension(475, 455));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_card.setMaximumSize(new java.awt.Dimension(470, 430));
        panel_card.setMinimumSize(new java.awt.Dimension(470, 430));
        panel_card.setPreferredSize(new java.awt.Dimension(470, 430));
        panel_card.setLayout(new java.awt.CardLayout());

        panel_visOrdre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_visOrdre.setMaximumSize(new java.awt.Dimension(470, 430));
        panel_visOrdre.setMinimumSize(new java.awt.Dimension(470, 430));
        panel_visOrdre.setPreferredSize(new java.awt.Dimension(470, 430));
        panel_visOrdre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Kunde info"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Navn");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Adresse");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Post nr by");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tlf nr");

        jLabel_VisNavn.setText("jLabel8");

        jLabel_VisAdresse.setText("jLabel12");

        jLabel_VisPostnrBy.setText("jLabel13");

        jLabel_VisTlf.setText("jLabel14");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_VisTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel_VisPostnrBy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addComponent(jLabel_VisAdresse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_VisNavn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(141, 141, 141))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_VisNavn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_VisAdresse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_VisPostnrBy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_VisTlf)
                    .addComponent(jLabel4))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panel_visOrdre.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 210, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Vis Ordre");
        panel_visOrdre.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ordre info"));

        jLabel_VisLevDato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_VisLevDato.setText("jLabel16");

        jLabel_VisOprettet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_VisOprettet.setText("jLabel15");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Oprettet");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Lev. Dato");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Afh. Dato");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Provisions nr:");

        jLabel_VisAfhentDato.setText("jLabel17");

        jPanel3.setBackground(new java.awt.Color(211, 255, 216));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_VisPris.setBackground(new java.awt.Color(211, 255, 216));
        jLabel_VisPris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_VisPris.setText("jLabel5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_VisPris, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_VisPris)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_VisLevDato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_VisOprettet, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_VisAfhentDato)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel_VisProvision)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel_VisOprettet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_VisLevDato)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel_VisAfhentDato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel_VisProvision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_visOrdre.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Valgmuligheder"));

        jButton_OrdrePDF.setText("Ordre PDF");
        jButton_OrdrePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OrdrePDFActionPerformed(evt);
            }
        });

        jButton4.setText("Rediger");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton_FakturaPdf.setText("Faktura PDF");
        jButton_FakturaPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FakturaPdfActionPerformed(evt);
            }
        });

        jButton5.setText("Opgrader");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton_Kontopdf.setText("Konto PDF");
        jButton_Kontopdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KontopdfActionPerformed(evt);
            }
        });

        jButton7.setText("Slet");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_OrdrePDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_FakturaPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Kontopdf, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton7)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_FakturaPdf)
                    .addComponent(jButton_OrdrePDF)
                    .addComponent(jButton_Kontopdf))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panel_visOrdre.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 303, -1, 120));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ekstra Info")));

        jLabel_Afdødnavn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Afdødnavn.setText("Afdød navn:");

        jLabel_Kirkegård.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Kirkegård.setText("Kirkegård: ");

        jLabel_Række.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Række.setText("Række:");

        jLabel_NR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_NR.setText("Nr:");

        jLabel_Afdeling.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Afdeling.setText("Afdeling:");

        jLabel_Bemærkning.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Bemærkning.setText("Bemærkning:");

        jLabel_VisAfDødNavn.setText("Thomas Nielsen");

        jLabel_VisKirkegård.setText("Vester have kirkegård");

        jLabel_VisRække.setText("12");

        jLabel_VisNR.setText("14");

        jLabel_VisAfdeling.setText("13");

        jLabel_VisBemærkning.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_VisBemærkning.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Afdødnavn)
                    .addComponent(jLabel_Kirkegård)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_Række)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_VisRække, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_VisAfDødNavn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_VisKirkegård, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_NR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_VisNR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel_Afdeling)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_VisAfdeling, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_VisBemærkning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_Bemærkning)
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addComponent(jLabel_VisEkstraBemærkning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Afdødnavn)
                    .addComponent(jLabel_Bemærkning)
                    .addComponent(jLabel_VisAfDødNavn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Kirkegård)
                    .addComponent(jLabel_VisKirkegård)
                    .addComponent(jLabel_VisBemærkning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Række)
                    .addComponent(jLabel_NR)
                    .addComponent(jLabel_Afdeling)
                    .addComponent(jLabel_VisRække)
                    .addComponent(jLabel_VisNR)
                    .addComponent(jLabel_VisAfdeling)
                    .addComponent(jLabel_VisEkstraBemærkning))
                .addGap(62, 62, 62))
        );

        panel_visOrdre.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 213, 440, 90));

        jLabel_fejl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_fejl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panel_visOrdre.add(jLabel_fejl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 330, 20));

        panel_card.add(panel_visOrdre, "visOrdre");

        panel_Opgrader.setMaximumSize(new java.awt.Dimension(470, 430));
        panel_Opgrader.setMinimumSize(new java.awt.Dimension(470, 430));
        panel_Opgrader.setPreferredSize(new java.awt.Dimension(470, 430));
        panel_Opgrader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Opgrader Faktura");
        panel_Opgrader.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        panel_faktura_info.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_faktura_info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_accepter.setText("Opgrader");
        button_accepter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_accepterActionPerformed(evt);
            }
        });
        panel_faktura_info.add(button_accepter, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        panel_fakturaInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_fakturaInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radioButton_NormalOrdre.setSelected(true);
        radioButton_NormalOrdre.setText("Privatperson");
        radioButton_NormalOrdre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_NormalOrdreActionPerformed(evt);
            }
        });
        panel_fakturaInfo.add(radioButton_NormalOrdre, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 9, -1, -1));

        radioButton_Bedemand.setText("Bedemand");
        radioButton_Bedemand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_BedemandActionPerformed(evt);
            }
        });
        panel_fakturaInfo.add(radioButton_Bedemand, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 9, -1, -1));

        textField_Faktura_nr.setEditable(false);
        panel_fakturaInfo.add(textField_Faktura_nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 32, 111, -1));

        textField_ordreNr.setEditable(false);
        panel_fakturaInfo.add(textField_ordreNr, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 58, 112, -1));

        label_ordre_nr.setText("Ordre_nr");
        panel_fakturaInfo.add(label_ordre_nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, -1, -1));

        label_faktura_nr.setText("Faktura_nr");
        panel_fakturaInfo.add(label_faktura_nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 35, -1, -1));

        textField_dato.setEditable(false);
        panel_fakturaInfo.add(textField_dato, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 84, 112, -1));

        label_dato.setText("Dato");
        panel_fakturaInfo.add(label_dato, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, -1, -1));

        panel_faktura_info.add(panel_fakturaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 120));

        panel_faktureringsadresse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_faktureringsadresse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_faktureringBy.setText("By");
        panel_faktureringsadresse.add(label_faktureringBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 89, -1, -1));

        label_faktureringPostNr.setText("Postnummer");
        panel_faktureringsadresse.add(label_faktureringPostNr, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, -1, -1));

        label_faktureringsadresse.setText("Adresse");
        panel_faktureringsadresse.add(label_faktureringsadresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 37, -1, -1));
        panel_faktureringsadresse.add(textField_faktureringAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 34, 114, -1));

        checkBox_faktureringsAdresse.setText("Anden faktureringsadresse");
        panel_faktureringsadresse.add(checkBox_faktureringsAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 9, -1, -1));
        panel_faktureringsadresse.add(textField_faktureringPostNr, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 60, 114, -1));
        panel_faktureringsadresse.add(textField_faktureringBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 86, 114, -1));

        panel_faktura_info.add(panel_faktureringsadresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 220, 120));

        panel_bedemandInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_bedemandInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_bedemand_firma.setText("Firmanavn");
        panel_bedemandInfo.add(label_bedemand_firma, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        label_bedemand_cvr.setText("CVR_nr");
        panel_bedemandInfo.add(label_bedemand_cvr, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, -1, -1));

        label_bedemand_adresse.setText("Adresse");
        panel_bedemandInfo.add(label_bedemand_adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 42, -1, -1));

        label_bedemand_postnr.setText("Postnummer");
        panel_bedemandInfo.add(label_bedemand_postnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 94, -1, -1));

        label_bedemand_by.setText("By");
        panel_bedemandInfo.add(label_bedemand_by, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, -1, -1));

        label_bedemand_bank.setText("Bank");
        panel_bedemandInfo.add(label_bedemand_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 68, -1, -1));

        label_bedemand_regnr.setText("Registrerings_nr");
        panel_bedemandInfo.add(label_bedemand_regnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 94, -1, -1));

        label_bedemand_kontonr.setText("Konto_nr");
        panel_bedemandInfo.add(label_bedemand_kontonr, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 120, -1, -1));
        panel_bedemandInfo.add(textField_bedemand_firma, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 13, 85, -1));
        panel_bedemandInfo.add(textField_bedemand_adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 39, 323, -1));
        panel_bedemandInfo.add(textField_bedemand_post, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 91, 86, -1));
        panel_bedemandInfo.add(textField_bedemand_by, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 117, 86, -1));
        panel_bedemandInfo.add(textField_bedemand_kontonr, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 117, 122, -1));
        panel_bedemandInfo.add(textField_bedemand_cvr, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 65, 86, -1));
        panel_bedemandInfo.add(textField_bedemand_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 65, 122, -1));
        panel_bedemandInfo.add(textField_bedemand_regnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 91, 122, -1));
        panel_bedemandInfo.add(textField_bedemand_tlf, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 13, 122, -1));

        label_bedemand_telefon.setText("Telefon");
        panel_bedemandInfo.add(label_bedemand_telefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 16, -1, -1));

        panel_faktura_info.add(panel_bedemandInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 430, 150));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_info_opgrader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_info_opgrader.setText("Kontoudtog og Provisionsseddel med numrene <Ordre_nr> vil også blive oprettet.");
        jPanel10.add(label_info_opgrader, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 397, 32));

        panel_faktura_info.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 430, -1));

        button_annuller.setText("Annuller");
        button_annuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_annullerActionPerformed(evt);
            }
        });
        panel_faktura_info.add(button_annuller, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        panel_Opgrader.add(panel_faktura_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 450, 370));

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panel_Opgrader.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 0, 240, 50));

        panel_card.add(panel_Opgrader, "Opgrader");

        getContentPane().add(panel_card, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OrdrePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OrdrePDFActionPerformed
    }//GEN-LAST:event_jButton_OrdrePDFActionPerformed

    private void jButton_FakturaPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FakturaPdfActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_FakturaPdfActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ((CardLayout) panel_card.getLayout()).show(panel_card, "Opgrader");
        startOpgradering();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton_KontopdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KontopdfActionPerformed
    }//GEN-LAST:event_jButton_KontopdfActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
int status = JOptionPane.showConfirmDialog(this, "Orden slettes fra systemet, er du sikker?", "Advarsel!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (status == 0) {
            try {
                dbhandler.deleteOrdre(ordre);
            } catch (SQLException ex) {
                jLabel_fejl.setText("Der skete en fejl ved sletning af orden");
                jLabel_fejl.setToolTipText("Fejl: " + ex);
            }
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void radioButton_NormalOrdreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_NormalOrdreActionPerformed
        radioButton_NormalOrdre.setSelected(true);
        radioButton_Bedemand.setSelected(false);
        enableView(panel_faktureringsadresse);
        disableView(panel_bedemandInfo);
        resetBedemandInfo();
        resetErrors();
    }//GEN-LAST:event_radioButton_NormalOrdreActionPerformed

    private void radioButton_BedemandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_BedemandActionPerformed
        radioButton_NormalOrdre.setSelected(false);
        radioButton_Bedemand.setSelected(true);
        enableView(panel_bedemandInfo);
        disableView(panel_faktureringsadresse);
        resetFaktureringsInfo();
        resetErrors();
    }//GEN-LAST:event_radioButton_BedemandActionPerformed

    private void button_accepterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_accepterActionPerformed
        if (validerInfo()) {
            boolean accept = visAcceptDialog("Er du sikker på at du vil opgradere til faktura?", "Bekræft opgradering");
            if (accept) {
                try {
                    if (radioButton_NormalOrdre.isSelected()) {
                        opretNormalOrdre();
                    } else {
                        opretBedemandOrdre();
                    }
                    ((CardLayout) panel_card.getLayout()).show(panel_card, "visOrdre");
                } catch (SQLException ex) {
                    errorLabel.setText("Problem med databasen, hold over denne besked for detaljer");
                    errorLabel.setToolTipText(ex.getMessage());
                } catch (ControlException ex) {
                    errorLabel.setText(ex.getMessage());
                    errorLabel.setToolTipText(ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_button_accepterActionPerformed

    private void button_annullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_annullerActionPerformed
        boolean accept = visAcceptDialog("Er du sikker på at du vil annullere opgradering af ordren?", "Annuller opgradering");
        if (accept) {
            ((CardLayout) panel_card.getLayout()).show(panel_card, "visOrdre");
        }
    }//GEN-LAST:event_button_annullerActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_accepter;
    private javax.swing.JButton button_annuller;
    private javax.swing.JCheckBox checkBox_faktureringsAdresse;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_FakturaPdf;
    private javax.swing.JButton jButton_Kontopdf;
    private javax.swing.JButton jButton_OrdrePDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Afdeling;
    private javax.swing.JLabel jLabel_Afdødnavn;
    private javax.swing.JLabel jLabel_Bemærkning;
    private javax.swing.JLabel jLabel_Kirkegård;
    private javax.swing.JLabel jLabel_NR;
    private javax.swing.JLabel jLabel_Række;
    private javax.swing.JLabel jLabel_VisAdresse;
    private javax.swing.JLabel jLabel_VisAfDødNavn;
    private javax.swing.JLabel jLabel_VisAfdeling;
    private javax.swing.JLabel jLabel_VisAfhentDato;
    private javax.swing.JLabel jLabel_VisBemærkning;
    private javax.swing.JLabel jLabel_VisEkstraBemærkning;
    private javax.swing.JLabel jLabel_VisKirkegård;
    private javax.swing.JLabel jLabel_VisLevDato;
    private javax.swing.JLabel jLabel_VisNR;
    private javax.swing.JLabel jLabel_VisNavn;
    private javax.swing.JLabel jLabel_VisOprettet;
    private javax.swing.JLabel jLabel_VisPostnrBy;
    private javax.swing.JLabel jLabel_VisPris;
    private javax.swing.JLabel jLabel_VisProvision;
    private javax.swing.JLabel jLabel_VisRække;
    private javax.swing.JLabel jLabel_VisTlf;
    private javax.swing.JLabel jLabel_fejl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel label_bedemand_adresse;
    private javax.swing.JLabel label_bedemand_bank;
    private javax.swing.JLabel label_bedemand_by;
    private javax.swing.JLabel label_bedemand_cvr;
    private javax.swing.JLabel label_bedemand_firma;
    private javax.swing.JLabel label_bedemand_kontonr;
    private javax.swing.JLabel label_bedemand_postnr;
    private javax.swing.JLabel label_bedemand_regnr;
    private javax.swing.JLabel label_bedemand_telefon;
    private javax.swing.JLabel label_dato;
    private javax.swing.JLabel label_faktura_nr;
    private javax.swing.JLabel label_faktureringBy;
    private javax.swing.JLabel label_faktureringPostNr;
    private javax.swing.JLabel label_faktureringsadresse;
    private javax.swing.JLabel label_info_opgrader;
    private javax.swing.JLabel label_ordre_nr;
    private javax.swing.JPanel panel_Opgrader;
    private javax.swing.JPanel panel_bedemandInfo;
    private javax.swing.JPanel panel_card;
    private javax.swing.JPanel panel_fakturaInfo;
    private javax.swing.JPanel panel_faktura_info;
    private javax.swing.JPanel panel_faktureringsadresse;
    private javax.swing.JPanel panel_visOrdre;
    private javax.swing.JRadioButton radioButton_Bedemand;
    private javax.swing.JRadioButton radioButton_NormalOrdre;
    private javax.swing.JTextField textField_Faktura_nr;
    private javax.swing.JTextField textField_bedemand_adresse;
    private javax.swing.JTextField textField_bedemand_bank;
    private javax.swing.JTextField textField_bedemand_by;
    private javax.swing.JTextField textField_bedemand_cvr;
    private javax.swing.JTextField textField_bedemand_firma;
    private javax.swing.JTextField textField_bedemand_kontonr;
    private javax.swing.JTextField textField_bedemand_post;
    private javax.swing.JTextField textField_bedemand_regnr;
    private javax.swing.JTextField textField_bedemand_tlf;
    private javax.swing.JTextField textField_dato;
    private javax.swing.JTextField textField_faktureringAdresse;
    private javax.swing.JTextField textField_faktureringBy;
    private javax.swing.JTextField textField_faktureringPostNr;
    private javax.swing.JTextField textField_ordreNr;
    // End of variables declaration//GEN-END:variables

    public boolean visAcceptDialog(String message, String title) {
        boolean accept = false;
        String[] options = new String[]{"Ja", "Nej"};
        int reply = JOptionPane.showOptionDialog(this, message, title, JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        if (reply == JOptionPane.YES_OPTION) {
            accept = true;
        }
        return accept;
    }

    public final void disableView(JPanel panel) {
        Component[] com = panel.getComponents();
        for (int a = 0; a < com.length; a++) {
            com[a].setEnabled(false);
        }
    }

    public final void enableView(JPanel panel) {
        Component[] com = panel.getComponents();
        for (int a = 0; a < com.length; a++) {
            com[a].setEnabled(true);
        }
    }

    private void startOpgradering() {
        enableView(panel_faktureringsadresse);
        disableView(panel_bedemandInfo);
        textField_Faktura_nr.setText(ordre.createFakturaNr());
        textField_ordreNr.setText(ordre.getOrdre_nr());
        textField_dato.setText(Utility.getCurrentTimeToString());
    }

    private void opretNormalOrdre() throws SQLException, ControlException {
        Faktura faktura;
        if (checkBox_faktureringsAdresse.isSelected()) {
            Postnummer post_nr = new Postnummer(Integer.parseInt(
                    textField_faktureringPostNr.getText().replace("'", "\'")),
                    textField_faktureringBy.getText().replace("'", "\'"));
            Faktureringsadresse adresse = new Faktureringsadresse(
                    0,
                    textField_faktureringAdresse.getText().replace("'", "\'"),
                    post_nr);
            faktura = new Faktura(ordre.createFakturaNr(),
                    Utility.getCurrentTime(),
                    Utility.getCurrentTime(),
                    adresse,
                    false,
                    false,
                    ordre,
                    null,
                    null);
        } else {
            faktura = new Faktura(ordre.createFakturaNr(),
                    Utility.getCurrentTime(),
                    Utility.getCurrentTime(),
                    null,
                    false,
                    false,
                    ordre,
                    null,
                    null);
        }

        dbhandler.createFaktura(faktura);
    }

    private void opretBedemandOrdre() throws SQLException, ControlException {
        Faktura faktura;
        Postnummer post_nr = new Postnummer(
                Integer.parseInt(textField_bedemand_post.getText()),
                textField_bedemand_by.getText().replace("'", "\'"));
        Samarbejdspartner bedemand = new Samarbejdspartner(
                textField_bedemand_firma.getText().replace("'", "\'"),
                textField_bedemand_adresse.getText().replace("'", "\'"),
                Integer.parseInt(textField_bedemand_tlf.getText()),
                Integer.parseInt(textField_bedemand_cvr.getText()),
                Integer.parseInt(textField_bedemand_regnr.getText()),
                textField_bedemand_kontonr.getText().replace("'", "\'"),
                textField_bedemand_bank.getText().replace("'", "\'"),
                post_nr);
        Kontoudtog kontoudtog = new Kontoudtog(
                ordre.getOrdre_nr(),
                Utility.getCurrentTime(),
                Utility.getCurrentTime());
        Provisionsseddel provisionsseddel = new Provisionsseddel(
                ordre.getOrdre_nr(),
                Utility.getCurrentTime(),
                kontoudtog);
        faktura = new Faktura(ordre.createFakturaNr(),
                Utility.getCurrentTime(),
                Utility.getCurrentTime(),
                null,
                true,
                false,
                ordre,
                bedemand,
                provisionsseddel);

        dbhandler.createFaktura(faktura);

    }

    public String validerString(String string) {
        String newString = string.replace("\\", "");
        return newString;
    }

    private boolean validerInfo() {
        boolean valid = true;
        resetErrors();
        String error = "Fejl på følgende input: ";
        boolean isNotFirst = false;

        if (radioButton_NormalOrdre.isSelected()) {
            if (checkBox_faktureringsAdresse.isSelected()) {
                if (textField_faktureringAdresse.getText().equals("")) {
                    label_faktureringsadresse.setForeground(Color.red);
                    error += label_faktureringsadresse.getText();
                    isNotFirst = true;
                    valid = false;
                } else {
                    String old = textField_faktureringAdresse.getText().trim();
                    String news = validerString(textField_faktureringAdresse.getText().trim());
                    if (!old.equals(news)) {
                        textField_faktureringAdresse.setText(validerString(textField_faktureringAdresse.getText().trim()));
                        label_faktureringsadresse.setForeground(Color.red);
                        error += label_faktureringsadresse.getText() + "(Fjernet specialtegn)";
                        valid = false;
                        isNotFirst = true;
                    }
                }
                if (textField_faktureringPostNr.getText().length() != 4 || !isInteger(textField_faktureringPostNr.getText())) {
                    label_faktureringPostNr.setForeground(Color.red);
                    if (isNotFirst) {
                        error += ", ";
                    }
                    error += label_faktureringPostNr.getText() + "(ikke et postnummer)";
                    isNotFirst = true;
                    valid = false;
                }
                if (textField_faktureringBy.getText().equals("")) {
                    label_faktureringBy.setForeground(Color.red);
                    if (isNotFirst) {
                        error += ", ";
                    }
                    error += label_faktureringBy.getText();
                    valid = false;
                } else {
                    String old = textField_faktureringBy.getText();
                    String news = validerString(textField_faktureringBy.getText().trim());
                    if (!old.equals(news)) {
                        textField_faktureringBy.setText(validerString(textField_faktureringBy.getText().trim()));
                        label_faktureringBy.setForeground(Color.red);
                        error += label_faktureringBy.getText() + "(Fjernet specialtegn)";
                        valid = false;
                    }
                }
            }
        } else {
            if (textField_bedemand_firma.getText().equals("")) {
                label_bedemand_firma.setForeground(Color.red);
                error += label_bedemand_firma.getText();
                isNotFirst = true;
                valid = false;
            } else {
                String old = textField_bedemand_firma.getText();
                String news = validerString(textField_bedemand_firma.getText().trim());
                if (!old.equals(news)) {
                    textField_bedemand_firma.setText(validerString(textField_bedemand_firma.getText().trim()));
                    label_bedemand_firma.setForeground(Color.red);
                    error += label_bedemand_firma.getText() + "(Fjernet specialtegn)";
                    isNotFirst = true;
                    valid = false;
                }
            }
            if (textField_bedemand_adresse.getText().equals("")) {
                label_bedemand_adresse.setForeground(Color.red);
                if (isNotFirst) {
                    error += ", ";
                }
                error += label_bedemand_adresse.getText();
                isNotFirst = true;
                valid = false;
            } else {
                String old = textField_bedemand_adresse.getText();
                String news = validerString(textField_bedemand_adresse.getText().trim());
                if (!old.equals(news)) {
                    textField_bedemand_adresse.setText(validerString(textField_bedemand_adresse.getText().trim()));
                    label_bedemand_adresse.setForeground(Color.red);
                    if (isNotFirst) {
                        error += ", ";
                    }
                    error += label_bedemand_adresse.getText() + "(Fjernet specialtegn)";
                    isNotFirst = true;
                    valid = false;
                }
            }
            if (textField_bedemand_bank.getText().equals("")) {
                label_bedemand_bank.setForeground(Color.red);
                if (isNotFirst) {
                    error += ", ";
                }
                error += label_bedemand_bank.getText();
                isNotFirst = true;
                valid = false;
            } else {
                String old = textField_bedemand_bank.getText();
                String news = validerString(textField_bedemand_bank.getText().trim());
                if (!old.equals(news)) {
                    textField_bedemand_bank.setText(validerString(textField_bedemand_bank.getText().trim()));
                    label_bedemand_bank.setForeground(Color.red);
                    if (isNotFirst) {
                        error += ", ";
                    }
                    error += label_bedemand_bank.getText() + "(Fjernet specialtegn)";
                    isNotFirst = true;
                    valid = false;
                }
            }
            if (textField_bedemand_by.getText().equals("")) {
                label_bedemand_by.setForeground(Color.red);
                if (isNotFirst) {
                    error += ", ";
                }
                error += label_bedemand_by.getText();
                isNotFirst = true;
                valid = false;
            } else {
                String old = textField_bedemand_by.getText();
                String news = validerString(textField_bedemand_by.getText().trim());
                if (!old.equals(news)) {
                    textField_bedemand_by.setText(validerString(textField_bedemand_by.getText().trim()));
                    label_bedemand_by.setForeground(Color.red);
                    if (isNotFirst) {
                        error += ", ";
                    }
                    error += label_bedemand_by.getText() + "(Fjernet specialtegn)";
                    isNotFirst = true;
                    valid = false;
                }
            }
            if (textField_bedemand_cvr.getText().length() != 8 || !isInteger(textField_bedemand_cvr.getText())) {
                label_bedemand_cvr.setForeground(Color.red);
                if (isNotFirst) {
                    error += ", ";
                }
                error += label_bedemand_cvr.getText() + "(CVR skal være på 8 cifre, og kun tal)";
                isNotFirst = true;
                valid = false;
            }
            if (textField_bedemand_post.getText().length() != 4 || !isInteger(textField_bedemand_post.getText())) {
                label_bedemand_postnr.setForeground(Color.red);
                if (isNotFirst) {
                    error += ", ";
                }
                error += label_bedemand_postnr.getText() + "(post_nr skal være på 4 cifre, og kun tal)";
                isNotFirst = true;
                valid = false;
            }
            if (textField_bedemand_regnr.getText().length() != 4 || !isInteger(textField_bedemand_regnr.getText())) {
                label_bedemand_regnr.setForeground(Color.red);
                if (isNotFirst) {
                    error += ", ";
                }
                error += label_bedemand_regnr.getText() + "(registrerings_nr skal være på 4 cifre, og kun tal)";
                isNotFirst = true;
                valid = false;
            }
            if (textField_bedemand_tlf.getText().length() != 8 || !isInteger(textField_bedemand_tlf.getText())) {
                label_bedemand_telefon.setForeground(Color.red);
                if (isNotFirst) {
                    error += ", ";
                }
                error += label_bedemand_telefon.getText() + "(Telefonnummer skal være på 8 cifre, og kun tal)";
                isNotFirst = true;
                valid = false;
            }
            //Validerer ikke om det kun er numre, skal lige have lavet en metode til det da det er på 
            //10 cifre og derfor ikke kan være i en integer
            if (textField_bedemand_kontonr.getText().length() != 10) {
                label_bedemand_kontonr.setForeground(Color.red);
                if (isNotFirst) {
                    error += ", ";
                }
                error += label_bedemand_kontonr.getText() + "(konto_nr skal være på 10 cifre, og kun tal)";
                valid = false;
            }
        }

        if (!valid) {
            errorLabel.setText("Fejl i input, hold over denne besked for detaljer.");
            errorLabel.setToolTipText(error);
        }

        return valid;
    }

    public boolean isInteger(String test) {
        boolean isInteger = true;
        try {
            Integer.parseInt(test);
        } catch (NumberFormatException ex) {
            isInteger = false;
        }
        return isInteger;
    }

    private void resetErrors() {
        errorLabel.setText("");
        label_bedemand_adresse.setForeground(Color.black);
        label_bedemand_firma.setForeground(Color.black);
        label_bedemand_by.setForeground(Color.black);
        label_bedemand_postnr.setForeground(Color.black);
        label_bedemand_cvr.setForeground(Color.black);
        label_bedemand_bank.setForeground(Color.black);
        label_bedemand_regnr.setForeground(Color.black);
        label_bedemand_kontonr.setForeground(Color.black);
        label_faktureringBy.setForeground(Color.black);
        label_faktureringPostNr.setForeground(Color.black);
        label_faktureringsadresse.setForeground(Color.black);
        label_bedemand_telefon.setForeground(Color.black);
    }

    private void resetFaktureringsInfo() {
        checkBox_faktureringsAdresse.setSelected(false);
        label_faktureringBy.setText("");
        label_faktureringPostNr.setText("");
        label_faktureringsadresse.setText("");
    }

    private void resetBedemandInfo() {
        textField_bedemand_adresse.setText("");
        textField_bedemand_by.setText("");
        textField_bedemand_post.setText("");
        textField_bedemand_firma.setText("");
        textField_bedemand_cvr.setText("");
        textField_bedemand_bank.setText("");
        textField_bedemand_kontonr.setText("");
        textField_bedemand_regnr.setText("");
    }
}
