/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.DocumentException;
import control.DBConnection;
import control.DatabaseObjectHandler;
import control.OpretRevisorSeddel;
import util.Utility;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.User;
import model.Vare;

/**
 *
 * @author T
 */
public class MainFrame extends javax.swing.JFrame {

    private DBConnection db;
    private DatabaseObjectHandler dbhandler;
    private Panel_OrdreSalg ordresalg;
    private Panel_LynSalg lynsalg;
    private Panel_Lager lager;
    private Panel_Søg søg;
    private Panel_CSVFiler csv;
    private Panel_Bruger bruger;
    private User user;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        user = null;
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            db = new DBConnection("localhost", "3306", "bejerholmstenhuggeri", "root", "root");

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        if (db.isConnected()) {

            dbhandler = new DatabaseObjectHandler(db);
            //Opret det panel som skal vises i framen
            opretPaneler();

            //   Man kan så bruge den her kode til at skifte panel når det er lavet til card. 
            ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "Hovedmenu");

        } else {
            // skift til vindue
        }
    }

    public MainFrame(DBConnection db, User user) {
        this.db = db;
        this.user = user;
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        java.net.URL url = ClassLoader.getSystemResource("img/icon.png");        
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(url);
        this.setIconImage(img);
        
        jLabel_dato.setText(Utility.getCurrentTimeToString());
        this.setLocationRelativeTo(null);

        jLabel_Brugernavn.setText(user.getUsername());

        if (db.isConnected()) {

            dbhandler = new DatabaseObjectHandler(db);
            //Opret det panel som skal vises i framen
            opretPaneler();

            //   Man kan så bruge den her kode til at skifte panel når det er lavet til card. 
            ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "Hovedmenu");

        } else {
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jPanel_Frame = new javax.swing.JPanel();
        jPanel_Hovedmenu = new javax.swing.JPanel();
        jButton_Administration = new javax.swing.JButton();
        jButton_Salg = new javax.swing.JButton();
        jButton_Lager = new javax.swing.JButton();
        jButton_Ordre = new javax.swing.JButton();
        jPanel_Administraion = new javax.swing.JPanel();
        jButton_BrugerAdministration = new javax.swing.JButton();
        jButton_Eksporter = new javax.swing.JButton();
        jButton_LagerOpgørelse = new javax.swing.JButton();
        jPanel_Salg = new javax.swing.JPanel();
        jButton_LynSalg = new javax.swing.JButton();
        jButton_OrdreSalg = new javax.swing.JButton();
        jButton_Hovedmenu = new javax.swing.JButton();
        jLabel_Loggedindsom = new javax.swing.JLabel();
        jLabel_Brugernavn = new javax.swing.JLabel();
        jButton_LogUd = new javax.swing.JButton();
        jLabel_dato = new javax.swing.JLabel();
        jLabel_BG = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bejerholm Stenhuggeri");
        setBackground(new java.awt.Color(200, 236, 255));
        setMinimumSize(new java.awt.Dimension(1000, 720));
        setPreferredSize(new java.awt.Dimension(1000, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Frame.setBackground(new java.awt.Color(0, 255, 102));
        jPanel_Frame.setOpaque(false);
        jPanel_Frame.setPreferredSize(new java.awt.Dimension(805, 510));
        jPanel_Frame.setLayout(new java.awt.CardLayout());

        jPanel_Hovedmenu.setOpaque(false);
        jPanel_Hovedmenu.setLayout(null);

        jButton_Administration.setText("Administration");
        jButton_Administration.setFocusable(false);
        jButton_Administration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdministrationActionPerformed(evt);
            }
        });
        jPanel_Hovedmenu.add(jButton_Administration);
        jButton_Administration.setBounds(420, 250, 180, 75);

        jButton_Salg.setText("Salg");
        jButton_Salg.setFocusable(false);
        jButton_Salg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalgActionPerformed(evt);
            }
        });
        jPanel_Hovedmenu.add(jButton_Salg);
        jButton_Salg.setBounds(190, 140, 180, 75);

        jButton_Lager.setText("Lager");
        jButton_Lager.setFocusable(false);
        jButton_Lager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LagerActionPerformed(evt);
            }
        });
        jPanel_Hovedmenu.add(jButton_Lager);
        jButton_Lager.setBounds(420, 140, 180, 75);

        jButton_Ordre.setText("Ordre");
        jButton_Ordre.setFocusable(false);
        jButton_Ordre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OrdreActionPerformed(evt);
            }
        });
        jPanel_Hovedmenu.add(jButton_Ordre);
        jButton_Ordre.setBounds(190, 250, 180, 75);

        jPanel_Frame.add(jPanel_Hovedmenu, "Hovedmenu");

        jPanel_Administraion.setOpaque(false);
        jPanel_Administraion.setLayout(null);

        jButton_BrugerAdministration.setText("Bruger Administration");
        jButton_BrugerAdministration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BrugerAdministrationActionPerformed(evt);
            }
        });
        jPanel_Administraion.add(jButton_BrugerAdministration);
        jButton_BrugerAdministration.setBounds(100, 170, 180, 75);

        jButton_Eksporter.setText("Eksporter");
        jButton_Eksporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EksporterActionPerformed(evt);
            }
        });
        jPanel_Administraion.add(jButton_Eksporter);
        jButton_Eksporter.setBounds(310, 170, 180, 75);

        jButton_LagerOpgørelse.setText("Lageropgørelse");
        jButton_LagerOpgørelse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LagerOpgørelseActionPerformed(evt);
            }
        });
        jPanel_Administraion.add(jButton_LagerOpgørelse);
        jButton_LagerOpgørelse.setBounds(520, 170, 180, 75);

        jPanel_Frame.add(jPanel_Administraion, "Administration");

        jPanel_Salg.setOpaque(false);
        jPanel_Salg.setLayout(null);

        jButton_LynSalg.setText("Lyn Salg");
        jButton_LynSalg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LynSalgActionPerformed(evt);
            }
        });
        jPanel_Salg.add(jButton_LynSalg);
        jButton_LynSalg.setBounds(190, 140, 180, 75);

        jButton_OrdreSalg.setText("Ordre Salg");
        jButton_OrdreSalg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OrdreSalgActionPerformed(evt);
            }
        });
        jPanel_Salg.add(jButton_OrdreSalg);
        jButton_OrdreSalg.setBounds(420, 140, 180, 75);

        jPanel_Frame.add(jPanel_Salg, "Salg");

        getContentPane().add(jPanel_Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jButton_Hovedmenu.setText("Hovedmenu");
        jButton_Hovedmenu.setFocusable(false);
        jButton_Hovedmenu.setOpaque(false);
        jButton_Hovedmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HovedmenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Hovedmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 112, -1, 21));

        jLabel_Loggedindsom.setText("Du er logged ind som:");
        getContentPane().add(jLabel_Loggedindsom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 120, 20));

        jLabel_Brugernavn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Brugernavn.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_Brugernavn.setText("jLabel3");
        getContentPane().add(jLabel_Brugernavn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 654, 220, 28));

        jButton_LogUd.setBackground(new java.awt.Color(172, 172, 172));
        jButton_LogUd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_LogUd.setText("Log ud");
        jButton_LogUd.setBorder(null);
        jButton_LogUd.setContentAreaFilled(false);
        jButton_LogUd.setFocusable(false);
        jButton_LogUd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogUdActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_LogUd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 40, 20));

        jLabel_dato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_dato.setText("jLabel2");
        getContentPane().add(jLabel_dato, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 657, 110, 20));

        jLabel_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.png"))); // NOI18N
        getContentPane().add(jLabel_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AdministrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdministrationActionPerformed
        ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "Administration");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AdministrationActionPerformed

    private void jButton_LynSalgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LynSalgActionPerformed
        ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "LynSalg");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LynSalgActionPerformed

    private void jButton_OrdreSalgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OrdreSalgActionPerformed
        ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "OrdreSalg");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_OrdreSalgActionPerformed

    private void jButton_HovedmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HovedmenuActionPerformed
        boolean accept = visAcceptDialog("Er du sikker på at du vil gå til hovedmenu'en?", "Gå til hovedmenu");
        if(accept){
        vishovedmenu();
        }
    }//GEN-LAST:event_jButton_HovedmenuActionPerformed

    private void jButton_BrugerAdministrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BrugerAdministrationActionPerformed
        ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "Bruger");
    }//GEN-LAST:event_jButton_BrugerAdministrationActionPerformed

    private void jButton_EksporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EksporterActionPerformed
        ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "Csv");         // TODO add your handling code here:
    }//GEN-LAST:event_jButton_EksporterActionPerformed

    private void jButton_LagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LagerActionPerformed
        ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "Lager");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LagerActionPerformed

    private void jButton_OrdreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OrdreActionPerformed
        ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "Søg");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_OrdreActionPerformed

    private void jButton_LagerOpgørelseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LagerOpgørelseActionPerformed
        try {
            int year = Calendar.getInstance().get(Calendar.YEAR);
            String dato = Utility.getCurrentTimeToString();
            OpretRevisorSeddel revisorseddel = new OpretRevisorSeddel(dato, year, db);
            revisorseddel.genererRevisorseddel("test2.pdf");

            Desktop desktop = Desktop.getDesktop();
            File file = new File("docs/test2.pdf");
            desktop.open(file);
        } catch (FileNotFoundException ex) {
            System.out.println("Luk andre pdf'er før du prøver at se en ny!");
        } catch (IOException ex) {
            ex.printStackTrace();
        } catch (DocumentException ex) {
            ex.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LagerOpgørelseActionPerformed

    private void jButton_SalgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalgActionPerformed
        ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "Salg");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_SalgActionPerformed

    private void jButton_LogUdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogUdActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LogUdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Administration;
    private javax.swing.JButton jButton_BrugerAdministration;
    private javax.swing.JButton jButton_Eksporter;
    private javax.swing.JButton jButton_Hovedmenu;
    private javax.swing.JButton jButton_Lager;
    private javax.swing.JButton jButton_LagerOpgørelse;
    private javax.swing.JButton jButton_LogUd;
    private javax.swing.JButton jButton_LynSalg;
    private javax.swing.JButton jButton_Ordre;
    private javax.swing.JButton jButton_OrdreSalg;
    private javax.swing.JButton jButton_Salg;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel_BG;
    private javax.swing.JLabel jLabel_Brugernavn;
    private javax.swing.JLabel jLabel_Loggedindsom;
    private javax.swing.JLabel jLabel_dato;
    private javax.swing.JPanel jPanel_Administraion;
    private javax.swing.JPanel jPanel_Frame;
    private javax.swing.JPanel jPanel_Hovedmenu;
    private javax.swing.JPanel jPanel_Salg;
    // End of variables declaration//GEN-END:variables

    public void skiftcard(Vare vare) {
        Panel_LynSalg lynsalg_ordre = new Panel_LynSalg(dbhandler, vare, this);
        jPanel_Frame.add(lynsalg_ordre);
        ((CardLayout) jPanel_Frame.getLayout()).addLayoutComponent(lynsalg_ordre, "LynSalg_Ordre");
        ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "LynSalg_Ordre");
    }

    public void vishovedmenu() {
        ((CardLayout) jPanel_Frame.getLayout()).show(jPanel_Frame, "Hovedmenu");
        opretPaneler();
    }

    public final void opretPaneler() {
        // opret paneler
        ordresalg = new Panel_OrdreSalg(dbhandler, this);
        lynsalg = new Panel_LynSalg(dbhandler, this);
        lager = new Panel_Lager(dbhandler, this);
        søg = new Panel_Søg(dbhandler, this);
        csv = new Panel_CSVFiler(db);
       // @@@@@@ Skal fjernes igen efter login er implementeret
        if(user != null){
             bruger = new Panel_Bruger(db, user);
        }else{
             bruger = new Panel_Bruger(db);
        }
       
        // tilføj det til vores jpanel der skal fremvise det
        jPanel_Frame.add(ordresalg);
        jPanel_Frame.add(lynsalg);
        jPanel_Frame.add(lager);
        jPanel_Frame.add(søg);
        jPanel_Frame.add(csv);
        jPanel_Frame.add(bruger);
        // Typecast panelet til cardlayout kald metoden addlayout med det panel der skal tilføjes samt en string der navngiver det. 
        ((CardLayout) jPanel_Frame.getLayout()).addLayoutComponent(ordresalg, "OrdreSalg");
        ((CardLayout) jPanel_Frame.getLayout()).addLayoutComponent(lynsalg, "LynSalg");
        ((CardLayout) jPanel_Frame.getLayout()).addLayoutComponent(lager, "Lager");
        ((CardLayout) jPanel_Frame.getLayout()).addLayoutComponent(søg, "Søg");
        ((CardLayout) jPanel_Frame.getLayout()).addLayoutComponent(csv, "Csv");
        ((CardLayout) jPanel_Frame.getLayout()).addLayoutComponent(bruger, "Bruger");
    }
    
    public boolean visAcceptDialog(String message, String title) {
        boolean accept = false;
        String[] options = new String[]{"Ja", "Nej"};
        int reply = JOptionPane.showOptionDialog(this, message, title, JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        if (reply == JOptionPane.YES_OPTION) {
            accept = true;
        }
        return accept;
    }
}
