/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JPanel;
import model.Vare;
import model.Vare_linje;

/**
 *
 * @author Anette
 */
public class Panel_OrdreSalgLinje extends javax.swing.JPanel {
    private Vare_linje varelinje;
    private Panel_OrdreSalg panel_ordresalg;
    
    /**
     * Creates new form Panel_OrdreSalgLinje
     */
    public Panel_OrdreSalgLinje(Vare_linje varelinje, Panel_OrdreSalg panel_ordresalg) {
        initComponents();
        this.varelinje = varelinje;
        this.panel_ordresalg = panel_ordresalg;
        
        if(varelinje.getVare() != null){
            jLabel2.setText(varelinje.getVare().getNavn()); 
            jLabel3.setText("Pris: "+varelinje.getVare().getSalgspris());
        } else if(varelinje.getTom_linje()!= null){
            jLabel2.setText(varelinje.getTom_linje().getNavn()); 
            jLabel3.setText("Pris: "+varelinje.getTom_linje().getSamletPris());
        } else if(varelinje.getInskription()!=null){
            
            jLabel2.setText(varelinje.getInskription().getTegntype().getNavn());
            jLabel3.setText("Pris: " + varelinje.getInskription().getPris());
        } 
        
        
       
        
    }
  public Vare_linje getVarelinje() {
        return varelinje;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setMinimumSize(new java.awt.Dimension(356, 40));
        setPreferredSize(new java.awt.Dimension(350, 38));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Vare navn");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setMaximumSize(new java.awt.Dimension(250, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 14));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 90, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deleteicon.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 32, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//           fjerner det valgte når der trykker på x
        panel_ordresalg.removepanel(this);
        
        
        //panel_ordresalg.drawpanel( (JPanel)this.getParent());

    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
