/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.DocumentException;
import control.DBConnection;
import control.DatabaseObjectHandler;
import control.ExportToCSV;
import control.OpretFaktura;
import control.OpretOrdre;
import control.exceptions.ControlException;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import model.Kunde;
import model.Ordre;
import model.Vare;
import model.Vare_linje;
import model.Varegruppe;

/**
 *
 * @author T
 */
public class Panel_LynSalg extends javax.swing.JPanel {

    private CardLayout layout;
    private ArrayList<Panel_LynSalgLinje> panel;
    private DBConnection db;
    private DatabaseObjectHandler dbhandler;
    private ArrayList<Varegruppe> varegrup_list;
    private ArrayList<Vare> vare_list;
    private ArrayList<Vare> valgteVare_lynsalg;
    private Kunde kunde;
    private double købssum;

    /**
     * Creates new form NewJPanel
     */
    public Panel_LynSalg(DatabaseObjectHandler dbhandler) {
        this.dbhandler = dbhandler;
        initComponents();
        købssum = 0;
        jLabel6.setText("" + købssum);
        layout = (CardLayout) (jPanel_MainCard.getLayout());
        try {
            kunde = dbhandler.getKunde(50111211);
        } catch (SQLException ex) {
            System.out.println("Der skete en fejl ved hentning af kunde.");;
        }
        vare_list = new ArrayList();
        valgteVare_lynsalg = new ArrayList();
        panel = new ArrayList();
        hentlister();
        udskrivVaregrp();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_MainCard = new javax.swing.JPanel();
        jPanel_LynSalg = new javax.swing.JPanel();
        jComboBox_Lynsalgvaregruppe = new javax.swing.JComboBox();
        jComboBoxLynsalgVare = new javax.swing.JComboBox();
        jButtonLynsalgTilføj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonLynsalgVidere = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaVareInfo = new javax.swing.JTextArea();
        jPanel_VareLinjer = new javax.swing.JPanel();
        jLabel_overskrift = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_fejlbesked = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel_OrdreBekræftigelse = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton13 = new javax.swing.JButton();
        jButton_Ændre = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel_købssum_lynsalg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_OversigtVarer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel_MainCard.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_MainCard.setOpaque(false);
        jPanel_MainCard.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel_MainCard.setLayout(new java.awt.CardLayout());

        jPanel_LynSalg.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_LynSalg.setOpaque(false);
        jPanel_LynSalg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox_Lynsalgvaregruppe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_LynsalgvaregruppeActionPerformed(evt);
            }
        });
        jPanel_LynSalg.add(jComboBox_Lynsalgvaregruppe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 40));

        jComboBoxLynsalgVare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLynsalgVareActionPerformed(evt);
            }
        });
        jPanel_LynSalg.add(jComboBoxLynsalgVare, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 270, 40));

        jButtonLynsalgTilføj.setText("Tilføj");
        jButtonLynsalgTilføj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLynsalgTilføjActionPerformed(evt);
            }
        });
        jPanel_LynSalg.add(jButtonLynsalgTilføj, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 220, 40));

        jLabel1.setText("Varegruppe: ");
        jPanel_LynSalg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setText("Varer:");
        jPanel_LynSalg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jButtonLynsalgVidere.setText("Videre");
        jButtonLynsalgVidere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLynsalgVidereActionPerformed(evt);
            }
        });
        jPanel_LynSalg.add(jButtonLynsalgVidere, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 453, 220, 30));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaVareInfo.setEditable(false);
        jTextAreaVareInfo.setBackground(new java.awt.Color(240, 240, 240));
        jTextAreaVareInfo.setColumns(20);
        jTextAreaVareInfo.setRows(5);
        jTextAreaVareInfo.setAutoscrolls(false);
        jTextAreaVareInfo.setBorder(null);
        jTextAreaVareInfo.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane5.setViewportView(jTextAreaVareInfo);

        jPanel_LynSalg.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 220, 210));

        jPanel_VareLinjer.setName("LynSalg"); // NOI18N
        jPanel_VareLinjer.setOpaque(false);
        jPanel_LynSalg.add(jPanel_VareLinjer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 490, 310));

        jLabel_overskrift.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_overskrift.setText("Lyn Salg");
        jPanel_LynSalg.add(jLabel_overskrift, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel3.setText("Vareinfo.");
        jPanel_LynSalg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));
        jPanel_LynSalg.add(jLabel_fejlbesked, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 220, 20));

        jLabel5.setText("Total pris");
        jPanel_LynSalg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");
        jPanel_LynSalg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 210, -1));

        jPanel_MainCard.add(jPanel_LynSalg, "card_LynSalg");

        jPanel_OrdreBekræftigelse.setOpaque(false);
        jPanel_OrdreBekræftigelse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel_OrdreBekræftigelse.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 35, 21, 290));

        jButton13.setText("Godkend");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel_OrdreBekræftigelse.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        jButton_Ændre.setText("Ændre");
        jButton_Ændre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ÆndreActionPerformed(evt);
            }
        });
        jPanel_OrdreBekræftigelse.add(jButton_Ændre, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 75, -1));

        jButton15.setText("Annuller");
        jPanel_OrdreBekræftigelse.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 75, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel38.setText("Ordre Bekræftigelse:");
        jPanel_OrdreBekræftigelse.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel_købssum_lynsalg.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_købssum_lynsalg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_købssum_lynsalg.setText("jLabel32");
        jPanel_OrdreBekræftigelse.add(jLabel_købssum_lynsalg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 434, 280, 40));

        jLabel4.setText("Samlet pris: ");
        jPanel_OrdreBekræftigelse.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        jPanel_OversigtVarer.setName("LynSalg"); // NOI18N
        jPanel_OversigtVarer.setOpaque(false);
        jPanel_OrdreBekræftigelse.add(jPanel_OversigtVarer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 580, 310));

        jPanel_MainCard.add(jPanel_OrdreBekræftigelse, "card_OrdreBekræftigelse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_MainCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_MainCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_LynsalgvaregruppeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_LynsalgvaregruppeActionPerformed
        jComboBoxLynsalgVare.removeAllItems();
        Varegruppe varegruppe = (Varegruppe) jComboBox_Lynsalgvaregruppe.getSelectedItem();
        try {
            vare_list = dbhandler.getVareListe(varegruppe.getGrp_nr());
            for (int i = 0; i < vare_list.size(); i++) {
                if(vare_list.get(i).getVareStatus() !=2){
                    jComboBoxLynsalgVare.addItem(vare_list.get(i));
                
                }
            }
        } catch (Exception e) {
            System.out.println("fejl: " + e);
        }
    }//GEN-LAST:event_jComboBox_LynsalgvaregruppeActionPerformed

    private void jComboBoxLynsalgVareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLynsalgVareActionPerformed
        jTextAreaVareInfo.setText("");
        if (jComboBoxLynsalgVare.getSelectedItem() != null) {
            Vare valgtvare = (Vare) jComboBoxLynsalgVare.getSelectedItem();
            jTextAreaVareInfo.append("" + valgtvare + "\n");
            jTextAreaVareInfo.append("Overflade: " + valgtvare.getOverflade() + "\n");
            jTextAreaVareInfo.append("Type: " + valgtvare.getTypenavn() + "\n");
            jTextAreaVareInfo.append("Højde: " + valgtvare.getHøjde() + "\n");
            jTextAreaVareInfo.append("Bredde: " + valgtvare.getBredde() + "\n");
            jTextAreaVareInfo.append("Pris" + valgtvare.getSalgspris() + "\n");
            jTextAreaVareInfo.append("Varegruppe: " + valgtvare.getGruppe() + "\n");
        }
    }//GEN-LAST:event_jComboBoxLynsalgVareActionPerformed

    private void jButtonLynsalgTilføjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLynsalgTilføjActionPerformed

        if (jComboBoxLynsalgVare.getItemCount() != 0) {

            Vare valgtvare = (Vare) jComboBoxLynsalgVare.getSelectedItem();
            valgteVare_lynsalg.add(valgtvare);
            vare_list.remove(valgtvare);
            Panel_LynSalgLinje linje = new Panel_LynSalgLinje(valgtvare, this);
            panel.add(linje);
            drawpanel(jPanel_VareLinjer);
            jLabel6.setText("" + udregnpris());


        } else {
            // Brugeren skal have besked om, at det ikke var muligt at tilføje vare da listen er tom
            jLabel_fejlbesked.setText("Der er ikke valgt nogen varer");
        }


    }//GEN-LAST:event_jButtonLynsalgTilføjActionPerformed

    private void jButtonLynsalgVidereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLynsalgVidereActionPerformed

        jLabel_købssum_lynsalg.setText("" + udregnpris());
        drawpanel(jPanel_OversigtVarer);
        layout.show(jPanel_MainCard, "card_OrdreBekræftigelse");
    }//GEN-LAST:event_jButtonLynsalgVidereActionPerformed

    private void jButton_ÆndreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ÆndreActionPerformed
        layout.show(jPanel_MainCard, "card_LynSalg");
        drawpanel(jPanel_VareLinjer);
    }//GEN-LAST:event_jButton_ÆndreActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        ArrayList<Vare_linje> varelinjer = new ArrayList();
        for (int i = 0; i < valgteVare_lynsalg.size(); i++) {
            Vare_linje linje = new Vare_linje(i, null, valgteVare_lynsalg.get(i), null, null);
            varelinjer.add(linje);

        }
        Ordre lynordre = new Ordre(kunde, varelinjer);
        System.out.println(lynordre.getCurrentTime());
        try {
            dbhandler.createOrdre(lynordre);
        } catch (Exception ex) {
            System.out.println("Der kunne ikke oprettes en ordre " + ex);
        }



        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButtonLynsalgTilføj;
    private javax.swing.JButton jButtonLynsalgVidere;
    private javax.swing.JButton jButton_Ændre;
    private javax.swing.JComboBox jComboBoxLynsalgVare;
    private javax.swing.JComboBox jComboBox_Lynsalgvaregruppe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_fejlbesked;
    private javax.swing.JLabel jLabel_købssum_lynsalg;
    private javax.swing.JLabel jLabel_overskrift;
    private javax.swing.JPanel jPanel_LynSalg;
    private javax.swing.JPanel jPanel_MainCard;
    private javax.swing.JPanel jPanel_OrdreBekræftigelse;
    private javax.swing.JPanel jPanel_OversigtVarer;
    private javax.swing.JPanel jPanel_VareLinjer;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextAreaVareInfo;
    // End of variables declaration//GEN-END:variables

    private void hentlister() {

        try {
            varegrup_list = dbhandler.getVaregruppeListe();

        } catch (Exception e) {
            System.out.println("ERRRWOR" + e);
        }

    }

    private void udskrivVaregrp() {
        for (int i = 0; i < varegrup_list.size(); i++) {
            jComboBox_Lynsalgvaregruppe.addItem(varegrup_list.get(i));

        }
    }

    /**
     * Denne metode bruges til at tegne de valgte ind i et jpanel.
     *
     * @param jpanel Den kaldes med det panel som den skal tegne på
     */
    public void drawpanel(JPanel jpanel) {
        System.out.println(jpanel.getName());
        jpanel.removeAll();
        jpanel.updateUI();
        for (int i = 0; i < panel.size(); i++) {
            jpanel.add(panel.get(i));
        }

    }

//Fjener en vare både fra array og panel
    public void removepanel(Panel_LynSalgLinje i) {
        panel.remove(i);
        valgteVare_lynsalg.remove(i.getVare());
        jLabel_købssum_lynsalg.setText("" + udregnpris());
        jLabel6.setText("" + udregnpris());

    }
// Bruges til at opdatere købssum når der fjernes en varer og der trykkes på videre knappen.

    public double udregnpris() {

        købssum = 0;
        for (int i = 0; i < valgteVare_lynsalg.size(); i++) {
            købssum = købssum + valgteVare_lynsalg.get(i).getSalgspris();

        }


        return købssum;
    }

    public void flytvarelinje(Panel_LynSalgLinje i, boolean flytvej) {

        int plads = panel.indexOf(i);

        if (flytvej == true) {

            if (plads != panel.size() - 1) {
                Collections.swap(panel, plads, plads + 1);
                Collections.swap(valgteVare_lynsalg, plads, plads + 1);
            }
        } else {
            if (plads != 0) {
                Collections.swap(panel, plads, plads - 1);
                Collections.swap(valgteVare_lynsalg, plads, plads - 1);
            }
        }

        System.out.println("---------------------------------------");
        for (int j = 0; j < valgteVare_lynsalg.size(); j++) {
            System.out.println("" + valgteVare_lynsalg.get(j));

        }


    }
}
