/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DatabaseObjectHandler;
import model.Faktura;
import model.Ordre;
import util.Utility;

/**
 *
 * @author T
 */
public class Panel_Søg_Resultat extends javax.swing.JPanel {

    private Ordre ordre;
    private Faktura faktura;
    private DatabaseObjectHandler dbhandler;
    int type; // 0 = ordre
    // 1 = faktura

    /**
     * Creates new form Panel_Søg_Resultat
     */
    public Panel_Søg_Resultat(DatabaseObjectHandler dbhandler, Ordre ordre) {
        initComponents();
        type = 0;
        this.ordre = ordre;
        this.dbhandler = dbhandler;
        jLabel_Navn.setText(ordre.getKunde().getFornavn() + " " + ordre.getKunde().getEfternavn());
        jLabel_Navn.setToolTipText("Telefon nr: " + ordre.getKunde().getTlf());
        jLabel_OrdreNr.setText("" + ordre.getOrdre_nr());
        jLabel_beløb.setText(Utility.formatDoubleToKr(ordre.getTotal()));
        jLabel_beløb.setToolTipText("Beløb med moms: " + Utility.formatDoubleToKr(ordre.getTotalInklMoms()));
        jLabel_VisOprettetDato.setText(Utility.formatTimestampToString(ordre.getOrdredato()));

    }

    public Panel_Søg_Resultat(DatabaseObjectHandler dbhandler, Faktura faktura) {
        initComponents();
        type = 1;
        this.faktura = faktura;
        this.dbhandler = dbhandler;
        jLabel_Navn.setText(faktura.getOrdre().getKunde().getFornavn() + " " + faktura.getOrdre().getKunde().getFornavn());
        jLabel_Navn.setToolTipText("Telefon nr: " + faktura.getOrdre().getKunde().getTlf());
        jLabel_OrdreNr.setText("" + faktura.getFaktura_nr());
        jLabel_beløb.setText(Utility.formatDoubleToKr(faktura.getOrdre().getTotal()));
        jLabel_beløb.setToolTipText("Beløb med moms: " + Utility.formatDoubleToKr(faktura.getOrdre().getTotalInklMoms()));
        jLabel_VisOprettetDato.setText(Utility.formatTimestampToString(faktura.getFaktureringsdato()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton_VisOrdre = new javax.swing.JButton();
        jPanel_Beløb = new javax.swing.JPanel();
        jLabel_beløb = new javax.swing.JLabel();
        jPanel_OrdreInfo = new javax.swing.JPanel();
        jLabel_OprettetDato = new javax.swing.JLabel();
        jLabel_Navn = new javax.swing.JLabel();
        jLabel_VisOprettetDato = new javax.swing.JLabel();
        jLabel_OrdreNr = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(278, 78));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(278, 78));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_VisOrdre.setText("Vis");
        jButton_VisOrdre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VisOrdreActionPerformed(evt);
            }
        });
        add(jButton_VisOrdre, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 5, 105, 30));

        jPanel_Beløb.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_Beløb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_beløb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_beløb.setText("jLabel5");
        jPanel_Beløb.add(jLabel_beløb, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 8, 90, -1));

        add(jPanel_Beløb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 104, 30));

        jPanel_OrdreInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_OrdreInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_OprettetDato.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_OprettetDato.setText("Oprettet: ");
        jPanel_OrdreInfo.add(jLabel_OprettetDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel_Navn.setText("Navn: ");
        jPanel_OrdreInfo.add(jLabel_Navn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, -1));

        jLabel_VisOprettetDato.setText("jLabel3");
        jPanel_OrdreInfo.add(jLabel_VisOprettetDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel_OrdreNr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_OrdreNr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_OrdreNr.setText("Nr");
        jPanel_OrdreInfo.add(jLabel_OrdreNr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 82, 22));

        add(jPanel_OrdreInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 140, 64));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VisOrdreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VisOrdreActionPerformed
        if (type == 0) {
            JDialog_SøgOrdre visordre = new JDialog_SøgOrdre(null, true, dbhandler, ordre);
            visordre.setVisible(true);
        } else if (type == 1) {
            JDialog_SøgFaktura visfaktura = new JDialog_SøgFaktura(null, true, dbhandler, faktura);
            visfaktura.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_VisOrdreActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_VisOrdre;
    private javax.swing.JLabel jLabel_Navn;
    private javax.swing.JLabel jLabel_OprettetDato;
    private javax.swing.JLabel jLabel_OrdreNr;
    private javax.swing.JLabel jLabel_VisOprettetDato;
    private javax.swing.JLabel jLabel_beløb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Beløb;
    private javax.swing.JPanel jPanel_OrdreInfo;
    // End of variables declaration//GEN-END:variables
}
