/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DatabaseObjectHandler;
import model.Ordre;

/**
 *
 * @author NiklasRenner
 */
public class Panel_OpretFaktura extends javax.swing.JPanel {

private Ordre ordre;
private DatabaseObjectHandler dbhandler;

    public Panel_OpretFaktura(Ordre ordre, DatabaseObjectHandler dbhandler) {
        initComponents();
        this.ordre = ordre;
        this.dbhandler = dbhandler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fakturaOverskriftLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        fakturaOverskriftLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fakturaOverskriftLabel.setText("Opret Faktura");
        fakturaOverskriftLabel.setToolTipText("lol");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fakturaOverskriftLabel)
                .addContainerGap(664, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fakturaOverskriftLabel)
                .addContainerGap(467, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fakturaOverskriftLabel;
    // End of variables declaration//GEN-END:variables
}
